services:
  cashing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/ref
    environment:
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL}
      CM_API_URL: ${CM_API_URL}
      CM_API_KEY: ${CM_API_KEY}
    stdin_open: true
    tty: true
    restart: always